# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


#Country.create(name: "Afghanistan", abbreviated_name:"AFG")
#Country.create(name: "Albania", abbreviated_name:"ALB")
#Country.create(name: "Algeria", abbreviated_name:"DZA")
#Country.create(name: "American Samoa", abbreviated_name:"ASM")
#Country.create(name: "Andorra", abbreviated_name:"AND")
#Country.create(name: "Angola", abbreviated_name:"AGO")
#Country.create(name: "Anguilla", abbreviated_name:"AIA")
#Country.create(name: "Antarctica", abbreviated_name:"ATA")
#Country.create(name: "Antigua and Barbuda", abbreviated_name:"ATG")
#Country.create(name: "Argentina", abbreviated_name:"ARG")
#Country.create(name: "Armenia", abbreviated_name:"ARM")
#Country.create(name: "Aruba", abbreviated_name:"ABW")
#Country.create(name: "Australia", abbreviated_name:"AUS")
#Country.create(name: "Austria", abbreviated_name:"AUT")
#Country.create(name: "Azerbaijan", abbreviated_name:"AZE")
#Country.create(name: "Bahamas", abbreviated_name:"BHS")
#Country.create(name: "Bahrain", abbreviated_name:"BHR")
#Country.create(name: "Bangladesh", abbreviated_name:"BGD")
#Country.create(name: "Barbados", abbreviated_name:"BRB")
#Country.create(name: "Belarus", abbreviated_name:"BLR")
#Country.create(name: "Belgium", abbreviated_name:"BEL")
#Country.create(name: "Belize", abbreviated_name:"BLZ")
#Country.create(name: "Benin", abbreviated_name:"BEN")
#Country.create(name: "Bermuda", abbreviated_name:"BMU")
#Country.create(name: "Bhutan", abbreviated_name:"BTN")
#Country.create(name: "Bolivia", abbreviated_name:"BOL")
#Country.create(name: "Bonaire", abbreviated_name:"BES")
#Country.create(name: "Bosnia and Herzegovina", abbreviated_name:"BIH")
#Country.create(name: "Botswana", abbreviated_name:"BWA")
#Country.create(name: "Bouvet Island", abbreviated_name:"BVT")
#Country.create(name: "Brazil", abbreviated_name:"BRA")
#Country.create(name: "British Indian Ocean Territory", abbreviated_name:"IOT")
#Country.create(name: "Brunei Darussalam", abbreviated_name:"BRN")
#Country.create(name: "Bulgaria", abbreviated_name:"BGR")
#Country.create(name: "Burkina Faso", abbreviated_name:"BFA")
#Country.create(name: "Burundi", abbreviated_name:"BDI")
#Country.create(name: "Cambodia", abbreviated_name:"KHM")
#Country.create(name: "Cameroon", abbreviated_name:"CMR")
#Country.create(name: "Canada", abbreviated_name:"CAN")
#Country.create(name: "Cape Verde", abbreviated_name:"CPV")
#Country.create(name: "Cayman Islands", abbreviated_name:"CYM")
#Country.create(name: "Central African Republic", abbreviated_name:"CAF")
#Country.create(name: "Chad", abbreviated_name:"TCD")
#Country.create(name: "Chile", abbreviated_name:"CHL")
#Country.create(name: "China", abbreviated_name:"CHN")
#Country.create(name: "Christmas Island", abbreviated_name:"CXR")
#Country.create(name: "Cocos (Keeling) Islands", abbreviated_name:"CCK")
#Country.create(name: "Colombia", abbreviated_name:"COL")
#Country.create(name: "Comoros", abbreviated_name:"COM")
#Country.create(name: "Congo", abbreviated_name:"COG")
#Country.create(name: "Democratic Republic of the Congo", abbreviated_name:"COD")
#Country.create(name: "Cook Islands", abbreviated_name:"COK")
#Country.create(name: "Costa Rica", abbreviated_name:"CRI")
#Country.create(name: "Croatia", abbreviated_name:"HRV")
#Country.create(name: "Cuba", abbreviated_name:"CUB")
#Country.create(name: "Curacao", abbreviated_name:"CUW")
#Country.create(name: "Cyprus", abbreviated_name:"CYP")
#Country.create(name: "Czech Republic", abbreviated_name:"CZE")
#Country.create(name: "Cote d'Ivoire", abbreviated_name:"CIV")
#Country.create(name: "Denmark", abbreviated_name:"DNK")
#Country.create(name: "Djibouti", abbreviated_name:"DJI")
#Country.create(name: "Dominica", abbreviated_name:"DMA")
#Country.create(name: "Dominican Republic", abbreviated_name:"DOM")
#Country.create(name: "Ecuador", abbreviated_name:"ECU")
#Country.create(name: "Egypt", abbreviated_name:"EGY")
#Country.create(name: "El Salvador", abbreviated_name:"SLV")
#Country.create(name: "Equatorial Guinea", abbreviated_name:"GNQ")
#Country.create(name: "Eritrea", abbreviated_name:"ERI")
#Country.create(name: "Estonia", abbreviated_name:"EST")
#Country.create(name: "Ethiopia", abbreviated_name:"ETH")
#Country.create(name: "Falkland Islands (Malvinas)", abbreviated_name:"FLK")
#Country.create(name: "Faroe Islands", abbreviated_name:"FRO")
#Country.create(name: "Fiji", abbreviated_name:"FJI")
#Country.create(name: "Finland", abbreviated_name:"FIN")
#Country.create(name: "France", abbreviated_name:"FRA")
#Country.create(name: "French Guiana", abbreviated_name:"GUF")
#Country.create(name: "French Polynesia", abbreviated_name:"PYF")
#Country.create(name: "French Southern Territories", abbreviated_name:"ATF")
#Country.create(name: "Gabon", abbreviated_name:"GAB")
#Country.create(name: "Gambia", abbreviated_name:"GMB")
#Country.create(name: "Georgia", abbreviated_name:"GEO")
#Country.create(name: "Germany", abbreviated_name:"DEU")
#Country.create(name: "Ghana", abbreviated_name:"GHA")
#Country.create(name: "Gibraltar", abbreviated_name:"GIB")
#Country.create(name: "Greece", abbreviated_name:"GRC")
#Country.create(name: "Greenland", abbreviated_name:"GRL")
#Country.create(name: "Grenada", abbreviated_name:"GRD")
#Country.create(name: "Guadeloupe", abbreviated_name:"GLP")
#Country.create(name: "Guam", abbreviated_name:"GUM")
#Country.create(name: "Guatemala", abbreviated_name:"GTM")
#Country.create(name: "Guernsey", abbreviated_name:"GGY")
#Country.create(name: "Guinea", abbreviated_name:"GIN")
#Country.create(name: "Guinea-Bissau", abbreviated_name:"GNB")
#Country.create(name: "Guyana", abbreviated_name:"GUY")
#Country.create(name: "Haiti", abbreviated_name:"HTI")
#Country.create(name: "Heard Island and McDonald Mcdonald Islands", abbreviated_name:"HMD")
#Country.create(name: "Holy See (Vatican City State)", abbreviated_name:"VAT")
#Country.create(name: "Honduras", abbreviated_name:"HND")
#Country.create(name: "Hong Kong", abbreviated_name:"HKG")
#Country.create(name: "Hungary", abbreviated_name:"HUN")
#Country.create(name: "Iceland", abbreviated_name:"ISL")
#Country.create(name: "India", abbreviated_name:"IND")
#Country.create(name: "Indonesia", abbreviated_name:"IDN")
#Country.create(name: "Iran, Islamic Republic of", abbreviated_name:"IRN")
#Country.create(name: "Iraq", abbreviated_name:"IRQ")
#Country.create(name: "Ireland", abbreviated_name:"IRL")
#Country.create(name: "Isle of Man", abbreviated_name:"IMN")
#Country.create(name: "Israel", abbreviated_name:"ISR")
#Country.create(name: "Italy", abbreviated_name:"ITA")
#Country.create(name: "Jamaica", abbreviated_name:"JAM")
#Country.create(name: "Japan", abbreviated_name:"JPN")
#Country.create(name: "Jersey", abbreviated_name:"JEY")
#Country.create(name: "Jordan", abbreviated_name:"JOR")
#Country.create(name: "Kazakhstan", abbreviated_name:"KAZ")
#Country.create(name: "Kenya", abbreviated_name:"KEN")
#Country.create(name: "Kiribati", abbreviated_name:"KIR")
#Country.create(name: "Korea, Democratic People's Republic of", abbreviated_name:"PRK")
#Country.create(name: "Korea, Republic of", abbreviated_name:"KOR")
#Country.create(name: "Kuwait", abbreviated_name:"KWT")
#Country.create(name: "Kyrgyzstan", abbreviated_name:"KGZ")
#Country.create(name: "Lao People's Democratic Republic", abbreviated_name:"LAO")
#Country.create(name: "Latvia", abbreviated_name:"LVA")
#Country.create(name: "Lebanon", abbreviated_name:"LBN")
#Country.create(name: "Lesotho", abbreviated_name:"LSO")
#Country.create(name: "Liberia", abbreviated_name:"LBR")
#Country.create(name: "Libya", abbreviated_name:"LBY")
#Country.create(name: "Liechtenstein", abbreviated_name:"LIE")
#Country.create(name: "Lithuania", abbreviated_name:"LTU")
#Country.create(name: "Luxembourg", abbreviated_name:"LUX")
#Country.create(name: "Macao", abbreviated_name:"MAC")
#Country.create(name: "Macedonia, the Former Yugoslav Republic of", abbreviated_name:"MKD")
#Country.create(name: "Madagascar", abbreviated_name:"MDG")
#Country.create(name: "Malawi", abbreviated_name:"MWI")
#Country.create(name: "Malaysia", abbreviated_name:"MYS")
#Country.create(name: "Maldives", abbreviated_name:"MDV")
#Country.create(name: "Mali", abbreviated_name:"MLI")
#Country.create(name: "Malta", abbreviated_name:"MLT")
#Country.create(name: "Marshall Islands", abbreviated_name:"MHL")
#Country.create(name: "Martinique", abbreviated_name:"MTQ")
#Country.create(name: "Mauritania", abbreviated_name:"MRT")
#Country.create(name: "Mauritius", abbreviated_name:"MUS")
#Country.create(name: "Mayotte", abbreviated_name:"MYT")
#Country.create(name: "Mexico", abbreviated_name:"MEX")
#Country.create(name: "Micronesia, Federated States of", abbreviated_name:"FSM")
#Country.create(name: "Moldova, Republic of", abbreviated_name:"MDA")
#Country.create(name: "Monaco", abbreviated_name:"MCO")
#Country.create(name: "Mongolia", abbreviated_name:"MNG")
#Country.create(name: "Montenegro", abbreviated_name:"MNE")
#Country.create(name: "Montserrat", abbreviated_name:"MSR")
#Country.create(name: "Morocco", abbreviated_name:"MAR")
#Country.create(name: "Mozambique", abbreviated_name:"MOZ")
#Country.create(name: "Myanmar", abbreviated_name:"MMR")
#Country.create(name: "Namibia", abbreviated_name:"NAM")
#Country.create(name: "Nauru", abbreviated_name:"NRU")
#Country.create(name: "Nepal", abbreviated_name:"NPL")
#Country.create(name: "Netherlands", abbreviated_name:"NLD")
#Country.create(name: "New Caledonia", abbreviated_name:"NCL")
#Country.create(name: "New Zealand", abbreviated_name:"NZL")
#Country.create(name: "Nicaragua", abbreviated_name:"NIC")
#Country.create(name: "Niger", abbreviated_name:"NER")
#Country.create(name: "Nigeria", abbreviated_name:"NGA")
#Country.create(name: "Niue", abbreviated_name:"NIU")
#Country.create(name: "Norfolk Island", abbreviated_name:"NFK")
#Country.create(name: "Northern Mariana Islands", abbreviated_name:"MNP")
#Country.create(name: "Norway", abbreviated_name:"NOR")
#Country.create(name: "Oman", abbreviated_name:"OMN")
#Country.create(name: "Pakistan", abbreviated_name:"PAK")
#Country.create(name: "Palau", abbreviated_name:"PLW")
#Country.create(name: "Palestine, State of", abbreviated_name:"PSE")
#Country.create(name: "Panama", abbreviated_name:"PAN")
#Country.create(name: "Papua New Guinea", abbreviated_name:"PNG")
#Country.create(name: "Paraguay", abbreviated_name:"PRY")
#Country.create(name: "Peru", abbreviated_name:"PER")
#Country.create(name: "Philippines", abbreviated_name:"PHL")
#Country.create(name: "Pitcairn", abbreviated_name:"PCN")
#Country.create(name: "Poland", abbreviated_name:"POL")
#Country.create(name: "Portugal", abbreviated_name:"PRT")
#Country.create(name: "Puerto Rico", abbreviated_name:"PRI")
#Country.create(name: "Qatar", abbreviated_name:"QAT")
#Country.create(name: "Romania", abbreviated_name:"ROU")
#Country.create(name: "Russian Federation", abbreviated_name:"RUS")
#Country.create(name: "Rwanda", abbreviated_name:"RWA")
#Country.create(name: "Reunion", abbreviated_name:"REU")
#Country.create(name: "Saint Barthelemy", abbreviated_name:"BLM")
#Country.create(name: "Saint Helena", abbreviated_name:"SHN")
#Country.create(name: "Saint Kitts and Nevis", abbreviated_name:"KNA")
#Country.create(name: "Saint Lucia", abbreviated_name:"LCA")
#Country.create(name: "Saint Martin (French part)", abbreviated_name:"MAF")
#Country.create(name: "Saint Pierre and Miquelon", abbreviated_name:"SPM")
#Country.create(name: "Saint Vincent and the Grenadines", abbreviated_name:"VCT")
#Country.create(name: "Samoa", abbreviated_name:"WSM")
#Country.create(name: "San Marino", abbreviated_name:"SMR")
#Country.create(name: "Sao Tome and Principe", abbreviated_name:"STP")
#Country.create(name: "Saudi Arabia", abbreviated_name:"SAU")
#Country.create(name: "Senegal", abbreviated_name:"SEN")
#Country.create(name: "Serbia", abbreviated_name:"SRB")
#Country.create(name: "Seychelles", abbreviated_name:"SYC")
#Country.create(name: "Sierra Leone", abbreviated_name:"SLE")
#Country.create(name: "Singapore", abbreviated_name:"SGP")
#Country.create(name: "Sint Maarten (Dutch part)", abbreviated_name:"SXM")
#Country.create(name: "Slovakia", abbreviated_name:"SVK")
#Country.create(name: "Slovenia", abbreviated_name:"SVN")
#Country.create(name: "Solomon Islands", abbreviated_name:"SLB")
#Country.create(name: "Somalia", abbreviated_name:"SOM")
#Country.create(name: "South Africa", abbreviated_name:"ZAF")
#Country.create(name: "South Georgia and the South Sandwich Islands", abbreviated_name:"SGS")
#Country.create(name: "South Sudan", abbreviated_name:"SSD")
#Country.create(name: "Spain", abbreviated_name:"ESP")
#Country.create(name: "Sri Lanka", abbreviated_name:"LKA")
#Country.create(name: "Sudan", abbreviated_name:"SDN")
#Country.create(name: "Suriname", abbreviated_name:"SUR")
#Country.create(name: "Svalbard and Jan Mayen", abbreviated_name:"SJM")
#Country.create(name: "Swaziland", abbreviated_name:"SWZ")
#Country.create(name: "Sweden", abbreviated_name:"SWE")
#Country.create(name: "Switzerland", abbreviated_name:"CHE")
#Country.create(name: "Syrian Arab Republic", abbreviated_name:"SYR")
#Country.create(name: "Taiwan, Province of China", abbreviated_name:"TWN")
#Country.create(name: "Tajikistan", abbreviated_name:"TJK")
#Country.create(name: "United Republic of Tanzania", abbreviated_name:"TZA")
#Country.create(name: "Thailand", abbreviated_name:"THA")
#Country.create(name: "Timor-Leste", abbreviated_name:"TLS")
#Country.create(name: "Togo", abbreviated_name:"TGO")
#Country.create(name: "Tokelau", abbreviated_name:"TKL")
#Country.create(name: "Tonga", abbreviated_name:"TON")
#Country.create(name: "Trinidad and Tobago", abbreviated_name:"TTO")
#Country.create(name: "Tunisia", abbreviated_name:"TUN")
#Country.create(name: "Turkey", abbreviated_name:"TUR")
#Country.create(name: "Turkmenistan", abbreviated_name:"TKM")
#Country.create(name: "Turks and Caicos Islands", abbreviated_name:"TCA")
#Country.create(name: "Tuvalu", abbreviated_name:"TUV")
#Country.create(name: "Uganda", abbreviated_name:"UGA")
#Country.create(name: "Ukraine", abbreviated_name:"UKR")
#Country.create(name: "United Arab Emirates", abbreviated_name:"ARE")
#Country.create(name: "United Kingdom", abbreviated_name:"GBR")
#Country.create(name: "United States", abbreviated_name:"USA")
#Country.create(name: "United States Minor Outlying Islands", abbreviated_name:"UMI")
#Country.create(name: "Uruguay", abbreviated_name:"URY")
#Country.create(name: "Uzbekistan", abbreviated_name:"UZB")
#Country.create(name: "Vanuatu", abbreviated_name:"VUT")
#Country.create(name: "Venezuela", abbreviated_name:"VEN")
#Country.create(name: "Viet Nam", abbreviated_name:"VNM")
#Country.create(name: "British Virgin Islands", abbreviated_name:"VGB")
#Country.create(name: "US Virgin Islands", abbreviated_name:"VIR")
#Country.create(name: "Wallis and Futuna", abbreviated_name:"WLF")
#Country.create(name: "Western Sahara", abbreviated_name:"ESH")
#Country.create(name: "Yemen", abbreviated_name:"YEM")
#Country.create(name: "Zambia", abbreviated_name:"ZMB")
#Country.create(name: "Zimbabwe", abbreviated_name:"ZWE")


#Event.create(name: '100 meter dash', gender: 'f', date: Time.now)
#Event.create(name: '100 meter dash', gender: 'm', date: Time.now)
#Event.create(name: '4x100 meter relay', gender: 'm', date: Time.now)
#Event.create(name: '4x100 meter relay', gender: 'f', date: Time.now)

j = Country.find_by('name': 'japan')
md_m = Event.find_by('name': '100 meter dash')
#Athlete.create(first_name: 'taro', last_name: 'japan', gender: 'm', country: j, event: md_m)
#Athlete.create(first_name: 'shingo', last_name: 'japan', gender: 'm', country: j)
#Athlete.create(first_name: 'shoji', last_name: 'japan', gender: 'm', country: j)
#Athlete.create(first_name: 'teppei', last_name: 'japan', gender: 'm', country: j)


a1 = Athlete.find_by(first_name: 'taro')
a2 = Athlete.find_by(first_name: 'shingo')
a3 = Athlete.find_by(first_name: 'shoji')
a4 = Athlete.find_by(first_name: 'teppei')
#t = Team.create!(
#	country: j,
#	event: md_m,
#	gender: 'm'
#)
#t.athletes = [a1, a2, a3, a4]


u = Country.find_by(abbreviated_name: 'usa')

b1 = Athlete.create(first_name: 'karan', last_name: 'america', gender: 'm', country: j)
b2 = Athlete.create(first_name: 'akasha', last_name: 'america', gender: 'm', country: j)
b3 = Athlete.create(first_name: 'amed', last_name: 'america', gender: 'm', country: j)
b4 = Athlete.create(first_name: 'luis', last_name: 'america', gender: 'm', country: j)

t = Team.create(country: u, gender: 'm')
t.athletes = [b1, b2, b3, b4]
t.save!

